### ISSUE TITLE
Curator UI Self-Service (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [Datastillery/smartcitiesdata#123]
Placeholder - XXL

**Comment by rob-h-m** [comment]
Closing - cards have been written

**Comment by JulieMaterni** [comment]
Original t-shirt size estimate was 55 points.

Reducing to 43 points due to the following cards being added: 
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/808 (3pts)
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/743 (3pts)
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/809 (3pts)
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/778 (3pts)

**Comment by JulieMaterni** [comment]
Increasing placeholder to 75 points. In talking with Jarred and Jake on 9/4, we feel this feature will be a similar level of effort as data curator MVP which was 96 points total. We'll have to work closely with Katie on prioritization to balance the size of the feature with value delivered.

**Comment by JulieMaterni** [comment]
Reducing to 65 points due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/252 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/253 (5pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/254 (2pts)

**Comment by JulieMaterni** [comment]
Reducing to 60 points due to the addition of the following cards: 

- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/262 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/common/499 (2pts)

**Comment by JulieMaterni** [comment]
Reducing to 63 points due to the addition of the following card: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/957 (2pts)

**Comment by JulieMaterni** [comment]
After refining MVP, new t-shirt size = 50 points

Updating to 38 points given the cards added above.

**Comment by JulieMaterni** [comment]
Reducing t-shirt size by 18 points due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/983 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/967 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/970 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/966 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/977 (1pt)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/978 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/979 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/980 (2pts)

Points remaining = 20 points

**Comment by JulieMaterni** [comment]
Reducing t-shirt size by 7 points due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/989 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/998 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/981 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/984 (1pt)

Points remaining = 13 points

**Comment by JulieMaterni** [comment]
Reducing t-shirt size by XX points due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1020 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1017 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1015 (1pt)

Points remaining = 8 points

**Comment by JulieMaterni** [comment]
Reducing t-shirt size by 4 points due to the addition of the following cards: 

- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1050 (2pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1047 (2pts)

Points remaining = 4 points

**Comment by JulieMaterni** [comment]
Reducing by 2 points due to the addition of the following card: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1047

Points remaining = 2

**Comment by JulieMaterni** [comment]
Clearing out placeholder due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/1081 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/305 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/306 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/307 (2pts)

**Comment by dmiree** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
