### ISSUE TITLE
CVE - generic push gateway (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [Datastillery/smartcitiesdata#127]
So hyuge and undefined, it gets TWO XXL placeholders for now

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

**Comment by JulieMaterni** [comment]
Based on conversation with Jarred 9/4, the plan will be to leave this placeholder as is and play a spike to determine how the system will handle large amounts of data and what might need to be enhanced. We'll revisit the t-shirt size after that spike is played.

**Comment by JulieMaterni** [comment]
Original t-shirt size = 55 points
Reducing to 42 points due to the addition of the following cards:

https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/944 (5pts)
https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/941 (3pts)
https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/940 (3pts)
https://app.zenhub.com/workspace/o/smartcolumbusos/scosopedia/issues/259 (2pts)

**Comment by JulieMaterni** [comment]
Reducing t-shirt size to 10 points. 

Possible remaining work: 
- Limiting number of messages that are sent to the OS (If Kapsch can do this, 1-2 point card. If we have to do this in the push gateway, 3-5 point card)
- Creating separate datasets for each message type - 2pts

**Comment by JulieMaterni** [comment]
Reducing placeholder to 8pts due to the addition of the following card: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/269 (2pts)

**Comment by dmiree** [comment]
Closing, as this was a placeholder card for grant forecasting purposes.
