### ISSUE TITLE
Using Extract Steps in Reaper (t-shirt)

### ISSUE THREAD

**Issue by carriebrinkley** [Datastillery/smartcitiesdata#802]

**Comment by JulieMaterni** [comment]
Updating t-shirt size to 18 points

**Comment by JulieMaterni** [comment]
Original = 18 points
Subtracting 11 points due to new cards
7 points remaining as of 9/14

Reducing to 7 points due to creating the following cards: 
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/884 (5pts)
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/889 (3pts)
- https://app.zenhub.com/workspace/o/smartcitiesdata/smartcitiesdata/issues/890 (3pts)

**Comment by JulieMaterni** [comment]
Current t-shirt size = 7pts
Reducing to 2pts due to the addition of the following cards: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/942 (3pts)
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/943 (2pts)

**Comment by JulieMaterni** [comment]
Zeroing out this t-shirt size due to the addition of the following card: 
- https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/datastillery/smartcitiesdata/965 (5pts)

**Comment by LtChae** [comment]
Closed, this has already been done.
